### PR TITLE
[RFR] Update init command wording

### PR DESCRIPTION
**Pull request by fzaninotto**
image

### CODE REVIEW

**Comment by Kmaschta** [comment]
Note: You can display the comfy server with `project.origin`

**Comment by fzaninotto** [comment]
Doesn't work. Here is what `project` looks like:

```js
{ id: 'ddd802fb-ce9e-45d5-b549-a018f4c73eac',
  name: 'testcomfy',
  accessKey: 'EALLFTCUDAANBGRTLOUL',
  readToken: '7VmrScknq52R0linzbQeJ4Pra2USe5xWAddqWloe',
  writeToken: '7dcfaX5jpT8eP65CwSzuvjBUVttUFxITWQHJnQ39',
  environments:
   [ { id: '23394c73-e401-414d-b006-903ee58a9f9d',
       name: 'development',
       configurations: [Object] } ] }
```

**Comment by Kmaschta** [comment]
My bad, you need to retrieve it from the config with:
```js
const { origin } = yield modules.project.retrieveFromConfig();
```

**Comment by fzaninotto** [comment]
Does not work:

```
Unable to locate the project identifier.
Please set COMFY_PROJECT_ID or edit your .comfy/config file.
Unable to locate the access key.
Please set COMFY_ACCESS_KEY or edit your .comfy/config file.
Unable to locate the secret token.
Please set COMFY_SECRET_TOKEN or edit your .comfy/config file.
Unable to locate the passphrase to decrypt your configs.
Please set COMFY_PASSPHRASE or edit your .comfy/config file.
Unable to locate the server origin to decrypt your configs.
Please set COMFY_ORIGIN or edit your .comfy/config file.
```

**Comment by Kmaschta** [comment]
You have to run this line after the `saveToConfig` instruction. Without it the file `.comfy/config` won't be created.

**Comment by fzaninotto** [comment]
Done. But I don't understand the rationale of asking interactive questions vs providing sensible defaults and let the user override them via options. 

e.g. 

```sh
> comfy init
# creates a project using the curent directory name, development environment, a generated passphrase
> comfy init --name foo
# creates a project using the the name 'foo', development environment, a generated passphrase
> comfy init --environments=development,staging,production
# you get the idea
```

Also, I don't understand that the URL of the origin server needs to be passed as env var rather than as an option to this command.

**Comment by Kmaschta** [comment]
I agree. In this way, we could have a command `comfy init help` to explain how it works.
I suggest to implement both: interactive and non-interactive modes.
The prompt will only ask for what is needed unless there is a `--no-interactive` flag, in that case it will throw an error.

**Pull request merged**
