### PR TITLE
api babel-env smallest

### PR DESCRIPTION
**Pull request by arturparkhisenko**
It was required to update "babel-core": "~6.7.7" to "~6.8.0".

### CODE REVIEW

**Comment by arturparkhisenko** [comment]
Adding back `add-module-exports`.

**Comment by Kmaschta** [comment]
Hey, what are the errors do you face with? Have you tried to run the E2E tests on your local env?

I have to admit that updating babel and/or webpack is not that easy on this project.

**Comment by arturparkhisenko** [comment]
@Kmaschta some of the packages breaks the build, all local tests ALWAYS green, that's why I testing it with TravisCI.

**Comment by arturparkhisenko** [comment]
@Kmaschta I'll continue tomorrow)

**Comment by arturparkhisenko** [comment]
@Kmaschta closing this, thanks, opened a new PR https://github.com/marmelab/comfygure/pull/113

**Pull request closed without merging**
